"""update column name

Revision ID: b90974df3613
Revises: 53971aac9f4b
Create Date: 2023-04-07 01:45:53.240591

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b90974df3613'
down_revision = '53971aac9f4b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('post', schema=None) as batch_op:
        batch_op.add_column(sa.Column('post_image', sa.String(length=50), nullable=True))
        batch_op.drop_column('image_file')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('post', schema=None) as batch_op:
        batch_op.add_column(sa.Column('image_file', sa.VARCHAR(length=50), nullable=True))
        batch_op.drop_column('post_image')

    # ### end Alembic commands ###
